# Cloud Build configuration for Open WebUI
# This file demonstrates how Cloud Build

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - '${_ARTIFACT_REGISTRY_URL}/open-webui:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest-image'
    args:
      - 'push'
      - '${_ARTIFACT_REGISTRY_URL}/open-webui:latest'
    waitFor: [ 'build-image' ]

# Substitutions for environment-specific values
substitutions:
  # These are filled by Terraform during trigger creation
  _ARTIFACT_REGISTRY_URL: 'us-central1-docker.pkg.dev/PROJECT_ID/REPO_NAME'
  _ENVIRONMENT: 'dev'

# Build timeout (20 minutes)
timeout: '1200s'

# Build options
options:
  # Use high-CPU machine for faster builds
  machineType: 'E2_HIGHCPU_8'

  # Use Cloud Logging for better integration
  logging: 'CLOUD_LOGGING_ONLY'

  # Enable streaming logs for real-time feedback
  logStreamingOption: STREAM_ON

# Image tags for organization
tags:
  - 'open-webui'
  - '${_ENVIRONMENT}'
