version: '3.8'

services:
  openwebui:
    build: .
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - DATABASE_URL=postgresql://openwebui:${DB_PASSWORD}@localhost:5432/openwebui
      - DATA_DIR=/app/backend/data
      - ENABLE_SIGNUP=false
      - ENABLE_LOGIN_FORM=true
    volumes:
      - openwebui-data:/app/backend/data
      - /tmp/cloudsql:/cloudsql
    depends_on:
      - cloud-sql-proxy
    networks:
      - openwebui-network

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
    container_name: cloud-sql-proxy
    restart: unless-stopped
    command: /cloud_sql_proxy -instances=${DB_CONNECTION_NAME}=tcp:0.0.0.0:5432 -credential_file=/config/key.json
    volumes:
      - /opt/openwebui/service-account-key.json:/config/key.json
      - /tmp/cloudsql:/cloudsql
    networks:
      - openwebui-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - openwebui
    networks:
      - openwebui-network

volumes:
  openwebui-data:

networks:
  openwebui-network:
    driver: bridge
